# Generated by Django 4.0.4 on 2022-07-01 15:59

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Efectivo egresado')),
                ('activo', models.IntegerField(verbose_name='activo')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on', verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Dinero ingresado')),
                ('activo', models.IntegerField(verbose_name='activo')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on', verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=35, verbose_name='titulo')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('activo', models.IntegerField(verbose_name='activo')),
                ('fecha_ejecucion', models.DateField(help_text='Date execution', verbose_name='fecha ejecucion')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on', verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(max_length=255, verbose_name='total mensual')),
                ('ahorro', models.IntegerField(max_length=255, verbose_name='ahorro mensual')),
                ('gastos', models.IntegerField(max_length=255, verbose_name='gasto mensual')),
                ('ahorro_anual', models.IntegerField(max_length=255, verbose_name='ahorro anual')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('activo', models.IntegerField(verbose_name='Activo')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
